name: Package - macOS - arm

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

  workflow_call:

jobs:
  macos:
    name: macOS Apps
    runs-on: macos-14
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Install build dependencies
        run: brew install --formula dylibbundler

      - name: Install library dependencies
        run: brew install --formula sdl2 sdl2_mixer sdl12-compat physfs glew libogg mpg123 flac fluid-synth

      - name: Install OpenVR SDK
        run: |
          curl -L -o openvr.zip https://github.com/ValveSoftware/openvr/archive/refs/tags/v2.12.14.zip
          unzip openvr.zip
          cd openvr-2.12.14
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_UNIVERSAL=OFF
          cmake --build build
          sudo cmake --install build
          cd ..
          rm -rf openvr.zip openvr-2.12.14

      - name: Configure D1
        run: cmake -S d1 -B buildd1 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build D1
        run: cmake --build buildd1

      - name: Configure D2
        run: cmake -S d2 -B buildd2 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build D2
        run: cmake --build buildd2

      - name: Configure D2 VR
        run: cmake -S d2 -B buildd2-vr -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPENVR=ON

      - name: Build D2 VR
        run: cmake --build buildd2-vr

      - name: Package
        run: ./contrib/packaging/macos/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm
          path: '*.zip'
